# Generated by Django 5.0.3 on 2024-04-08 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_restaurant_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='nickname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
