# Generated by Django 5.0.3 on 2024-03-28 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_sale_restaurant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='longitute',
            new_name='longitude',
        ),
    ]
